#!/bin/bash
MBOXES=(Hobby Personal)

STATUS=""
for m in "${MBOXES[@]}"; do
  COUNT=$(find ~/Mail/$m/Inbox/new -type f | wc -l)
  if [ $COUNT -gt 0 ];
  then
    STATUS="$STATUS $m[$COUNT]"
  fi
done

if [ "" == "$STATUS" ];
then
  echo ""
  exit 0
else
  echo " $STATUS"
  exit 33
fi
